const data={
    products:[
        {
            _id: '1',
      name: 'Barcelona Shirt',
      category: 'Shirts',
      image: '/images/Barcelona.jpg',
      price: 80,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: '2021/2022 Barcelona home shirt',
        },
        {
            _id: '2',
            name: 'West Ham Shirt',
            category: 'Shirts',
            image: '/images/WestHam.jpg',
            price: 65,
            countInStock: 0,
            brand: 'Umbro',
            rating: 4.8,
            numReviews: 17,
            description: '2021/2022 west ham home shirt',
          },
          {
            _id: '3',
            name: 'Real Madrid Shirt',
            category: 'Shirts',
            image: '/images/RealMadrid.jpg',
            price: 100,
            countInStock: 20,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: '2021/2022 Real Madrid home shirt',
          },
          {
            _id: '4',
            name: 'Champions League ball',
            category: 'Balls',
            image: '/images/ChampionsLeague.jpg',
            price: 120,
            countInStock: 15,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 14,
            description: 'Official 2021/2022 champions league ball',
          },
          {
            _id: '5',
            name: 'Euro 2020 ball',
            category: 'Balls',
            image: '/images/Euro2020.jpg',
            price: 80,
            countInStock: 5,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            description: 'Official Euro 2020 ball',
          },
          {
            _id: '6',
            name: 'Bundesliga ball',
            category: 'Balls',
            image: '/images/Bundesliga.jpg',
            price: 95,
            countInStock: 12,
            brand: 'Select',
            rating: 4.5,
            numReviews: 15,
            description: 'Official 2021/2022 bundesliga ball',
          },
    ]
}

export default data;